## Exercises

This will be a notebook for you to work through the exercises during the workshop. Feel free to work on these at whatever pace you feel works for you, but I encourage you to work together! Edit the title of this notebook with your name because I will ask you to upload your final notebook to our shared github repository at the end of this workshop.

Feel free to google the documentation for numpy, matplotlib, etc.

Don't forget to start by importing any libraries you need.

In [2]:
import numpy as np

### Day 1

#### Exercise 1

   A. Create an array with 10 evenly spaced values in logspace ranging from 0.1 to 10,000.

   B. Print the following values: The first value in the array, the final value in the array, and the range of 5th-8th values.

   C. Append the numbers 10,001 and 10,002 (as floats) to the array. Make sure you define this!

   D. Divide your new array by 2.

   E. Reshape your array to be 3 x 4. 

   F. Multiply your array by itself.
    
   G.  Print out the number of dimensions and the maximum value.

In [3]:
# EXERCISE A
log_array = np.array(np.logspace(-1,4,10))
print(log_array)

[1.00000000e-01 3.59381366e-01 1.29154967e+00 4.64158883e+00
 1.66810054e+01 5.99484250e+01 2.15443469e+02 7.74263683e+02
 2.78255940e+03 1.00000000e+04]


In [4]:
# EXERCISE B
print(log_array[4:8])
#This is inclusive of the 8th element (index 7)

[ 16.68100537  59.94842503 215.443469   774.26368268]


In [5]:
# EXERCISE C
new_log_array = np.append(log_array,[10001.,10002.])
print(new_log_array)

[1.00000000e-01 3.59381366e-01 1.29154967e+00 4.64158883e+00
 1.66810054e+01 5.99484250e+01 2.15443469e+02 7.74263683e+02
 2.78255940e+03 1.00000000e+04 1.00010000e+04 1.00020000e+04]


In [6]:
# EXERCISE D
div2_array = new_log_array/2
print(div2_array)

[5.00000000e-02 1.79690683e-01 6.45774833e-01 2.32079442e+00
 8.34050269e+00 2.99742125e+01 1.07721735e+02 3.87131841e+02
 1.39127970e+03 5.00000000e+03 5.00050000e+03 5.00100000e+03]


In [7]:
# EXERCISE E
inv_array = np.reshape(div2_array,(3,4))
print(inv_array)

[[5.00000000e-02 1.79690683e-01 6.45774833e-01 2.32079442e+00]
 [8.34050269e+00 2.99742125e+01 1.07721735e+02 3.87131841e+02]
 [1.39127970e+03 5.00000000e+03 5.00050000e+03 5.00100000e+03]]


In [13]:
# EXERCISE F
mult_array = np.dot(inv_array, np.transpose(inv_array))
print(mult_array)

[[5.83790060e+00 9.73820513e+02 1.58035073e+04]
 [9.73820513e+02 1.62443052e+05 2.63618391e+06]
 [1.58035073e+04 2.63618391e+06 7.69506605e+07]]


In [14]:
# EXERCISE G
array_dim = np.ndim(mult_array)
print(str(array_dim)+' dimensions')
print('Max = '+str(np.max(mult_array)))

2 dimensions
Max = 76950660.45670283
